@baseUrl = http://localhost:3001/
@testId = 636cf684089d73f0db2d8832

### Delete
DELETE {{baseUrl}}api/persons/{{testId}}

### Add person
POST {{baseUrl}}api/persons
Content-Type: application/json

{
    "name": "Aleksi",
    "number": "050-123456"
}